# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: "90e15014"
    url: /
    weight: 10
  - name: Experience
    identifier: a604b48b
    url: experience/
    weight: 20
  - name: Environment
    identifier: 3fa40cc9
    url: environment/
    weight: 30
  - name: Presentations
    identifier: 60a03af0
    url: /#presentations
    weight: 40
  - name: Leadership
    identifier: c4231787
    url: leadership/
    weight: 50
  - name: Blog
    identifier: 98fa2817
    url: /#blog
    weight: 60
