# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    identifier: about
    url: /
    weight: 10
  - name: Research
    identifier: research
    url: research/
    weight: 20
  - name: Experience
    identifier: experience
    url: experience/
    weight: 30
